{% set version = "1.4.0" %}

package:
  name: djangorestframework-xml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework-xml/djangorestframework-xml-{{ version }}.tar.gz
  sha256: d85d5744e75fe01ea2af667b15f6aa7df97c710516477ba493558da8432f6b0f

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - defusedxml >=0.3

test:
  imports:
    - rest_framework_xml

about:
  home: https://github.com/jpadilla/django-rest-framework-xml
  license: ISC
  # license_file: LICENSE not in the tarball
  summary: 'XML support for Django REST Framework'

extra:
  recipe-maintainers:
    - ocefpaf
