travis:
  secure:
    BINSTAR_TOKEN: l0h83+SSS/At4iAileVy+WwOWWvPhFf/8Bgsl7sxTMGMihbLtcD9uLOZFTAFNLIwbkmNQhNZGLlqd8HqtiSTUomharVr7Qv8NTNybSUlXimqP3Zigj72fpmLMqJXWNAtbDWz7Skgz2vt+7a8hTAUU+mLdlDuLitp9KGiCn/bf0tkArvgTu9ZulsAp07LizGq5cO9gUm0yow8BREetn8JqVFQqKCpqZnZNORqFenxtOmEv5B28wiONF5t59b7rWeq2UvpVuDO6RBVkORSt+t5cXf5UoaM9fZXksomI+1KCfUk9OFdGVC+C/H6967sICgZdxupQ0GGUVb6zWDd6+CBRTdQ3jedeIKwSlecYZrQiqUz078zfhcCMVX05DcgOMQZDB3F5a5WFNBw7UkvIhd/cwbwimpOBNahoMu59DXvNnQaIHlAaGxwKXUNGzBq6nfyg021vmwnc5NY018B3kr7LbCWvD4+kTB/UuySCvPinXkeVaoJUOhmUslASf6B5SU8vDdrWUy1pk/0eMPmEaBkYVhBBIt3Eu3K9BgLEbM2DhUsVP1iAdWrTg7SRa5eXLuwM/s0SI+U85fi+LSpNZVhSSGEaiBxfl0EXUKLz6hG0I7gdZ1BYfGLkElHI2fDLc+IRxXCgnMXNtVwx/vNWFfA8yYS2gZ8wRjSSLfLOGzmd4E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
