travis:
  secure:
    BINSTAR_TOKEN: GsIBpQMT/MvVM8QyMb9+zyeqosiXssb5Ve5Mp2LG1GvpC7tuNGUWwKFACLtf1XMZ6OpFU6BL9GuWjR1L8kpMAVEiRMTAMnPadXqz3LxItCBlxsD5b2rLb0Izn4bLTaPN2NojgWkycqrlyqPsWnLNDJHHjbI6OQTLA/OGUCKeujZg6+f0IKMKitcOclo5Sb81PGYeUTIQnMG9nogIKa4N4KhexqW1KklUjKofF9YPX+ZLfbkJ96nisGrx1Wv8Qp/+QFKfMQWveup94oq10JTCr1ugEqXJGjpUABJAcc3TOD9XrQ+o6g5Rm0DB/fAytMLwhaPg/Bu8kubvXiTKtiOLPWPyT4PPPsIAAXuFjI0nl30FKPHN/zhYg1p+mImPu7yAwnf6XMSvYbjZYIPeuRRGVgpkOqmVwTI1Zsh8pDsi3gc7R9YYlcrYaaAGRnFLOrWY2elTZPRm3fYc+9+cMIYJClVbHTrqNFsCmKjEsrwfY5JJSxecdhjSAp1UQUjPBhavb9Eu1NQJUHyXXDbdKyIRsZlxKzTiu0CeOZgORved1fm3JDIgo/wlqM5/MmfGjZpy3jmJdS9Y3Gc+YPDe+zH851GjOG/hRtO8gp9oaVzWomFdsYpE1VJHZrQ8MhD7dfa1+s4YLPGua8VBqRBuTvPj4yx3bv6GNFjzfx1oRSmYSns=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
